title: Hey!! I'm Lana
logo: /assets/Lana Image.jpg
description: Showcasing my data science projects and skills.
author: Lana Sisson
show_downloads: false
email: lana.sisson@outlook.com
theme: jekyll-theme-minimal
